### ISSUE TITLE
installation with make install really ?

### ISSUE THREAD

**Issue by Maziar123** [anametologin/krohnkite#1]
Hi

have you really installed from source by make install?

ed "s/\$VER/0.9.1/" res/metadata.json \
        | sed "s/\$REV/d5e3fc6/" \
        > pkg/metadata.json
./node_modules/typescript/bin/tsc
make: ./node_modules/typescript/bin/tsc: No such file or directory
make: *** [Makefile:81: krohnkite.js] Error 127

seems to use specific path for tsc ?

**Comment by anametologin** [comment]
Fixed.
