### ISSUE TITLE
Add Row (as opposed to Columnar) layout for vertical monitors.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [anametologin/krohnkite#10]
Would it be possible to add a new layout that works well with vertical monitors where the windows group vertically rather than horizontally? Currently all layouts that split the screen do so horizontally and when that's done on a vertical screen, everything is super narrow and hard to operate.

Additionally, thank you for making this port to Plasma 6. After using Polonium which is extremely buggy, you've been a life saver and I tremendously appreciate what you've done. ❤️

**Comment by Jas-SinghFSU** [comment]
I'm in the process of giving the implementation a go and hopefully I have something to contribute soon.

**Comment by anametologin** [comment]
Welcome to contribute.

**Comment by Jas-SinghFSU** [comment]
@anametologin As someone new to Kwin/Kwin-script development, may I ask how you view logs/changes without having to restart kwin_wayland after every `make install`? 

Whenever I seem to make changes, it appears that they're not reflected if I do either of - doing `make install` or doing `make build` and importing the kwin script file.

**Comment by anametologin** [comment]
> without having to restart 

> to make changes

I reboot every time. I haven't found the way.

**Comment by Jas-SinghFSU** [comment]
Coming along nicely, just have to fix some of the kinks and weird behavior.

![image](https://github.com/anametologin/krohnkite/assets/21210205/11f80f2b-8669-4431-be18-53f7df45dcb4)

**Comment by Jas-SinghFSU** [comment]
Question for you @anametologin, when implementing the Stacked layout, do we want each tile to be independent and split evenly? Or do we want to go with a more HalfSplit layout approach where every split will be a halved subsequently towards the bottom. Here are both approaches illustrated... Personally I'm more in favor of the half split stacked approach but I'm okay with implementing either depending on the feedback.

![image](https://github.com/anametologin/krohnkite/assets/21210205/4781737e-7e1b-41ed-82f7-63aae2ebd405)
![image](https://github.com/anametologin/krohnkite/assets/21210205/239dc732-d935-47ff-a784-a1eff0f3c090)

**Comment by anametologin** [comment]
Evenly stacked path more convenient for me a little but I never work with vertical monitor so I will not insist, I leave it for your choice.  If you has implemented the both may be better add checkbox in settings beside "stacked layout"?

**Comment by Jas-SinghFSU** [comment]
I settled for something between the 2 approaches where there will be a master tile that occupies the top half (initially... can be adjust of course) and the the bottom half is all the new windows evenly split within the bottom half.

This lets you have a master tile that you can swap between and retain the size of the master tile.

**Comment by Jas-SinghFSU** [comment]
#16

**Comment by Jas-SinghFSU** [comment]
Closed by 61522442698908763ee6265af340cd1871c418ca
