### ISSUE TITLE
Ultrawide monitor: set window maximum size

### ISSUE THREAD

**Issue by jbeaurivage** [anametologin/krohnkite#101]
I don't know if what I'm after is possible, but I figured I'd try to ask anyways. 
For users with ultrawide monitors, when there is only one window open, it fills the entire display, which is annoying because it is huge. Usually I will open two other "placeholder" windows in three-column layout that, while I'm not actively using, are just there to resize the main window to something more manageable.

Would it be possible to set the maximum window size (and possibly center that window) when only one window is on the desktop?

**Comment by anametologin** [comment]
> when only one window is on the desktop

You can make the window  float.

**Comment by jbeaurivage** [comment]
Indeed, I was hoping to automate that process, perhaps through window rules. Seems like windows don't respect the maximum size rule; I'm assuming krohbkite is overriding it? Otherwise, is there a way to float the window using rules?

**Comment by anametologin** [comment]
> I'm assuming krohbkite is overriding it?

The kwin script resizes a window and can assign and remove window props.

> Otherwise, is there a way to float the window using rules?

If you mean Krohnkite rules, you can permanently filter certain class windows but don't think that what you want. If you mean global window rules - no, the script will override it.

**Comment by jbeaurivage** [comment]
Sounds good, looks like there's no way to achieve what I'm thinking about without adding support in krohnkite. Please feel free to close this issue if that's not something you with to support.

**Comment by anametologin** [comment]
e803e8d8a7ca44c5f5b3ba8c0f9652c4228ac159

**Comment by icecreammatt** [comment]
Is there a way to make the sole window have 50% width but 100% height? Your change works well but its also squishing my browser vertically.

**Comment by anametologin** [comment]
52f0d577758c1ff517ef8025978f5c3db17a2dd9
[krohnkite-0.9.8.5.kwinscript.zip](https://github.com/user-attachments/files/18406977/krohnkite-0.9.8.5.kwinscript.zip)
