### ISSUE TITLE
Cycle Layout no longer an option?

### ISSUE THREAD

**Issue by MichaelGame-Dev** [anametologin/krohnkite#107]
**Symptom**
Was getting this setup, the default keybinds mention a cycle layout option. I'm guessing this has been switched for next layout and prev layout?

**How to Reproduce**
1. See documention
2. Search for cycle layout shortcut

**Expected behavior**
Find cycle layout shortcut option or updated documention.

**Notes**
Glad to put together a  pull request to update this (or anything else provided you send the info).

**Comment by anametologin** [comment]
readme updated
Meta + \ 	Next Layout
Meta + | 	Previous Layout
