### ISSUE TITLE
Tiled windows do not respect the "Windows Go Below" panel setting.

### ISSUE THREAD

**Issue by amolinae06** [anametologin/krohnkite#11]
**Symptom**
Thanks for maintaining this amazing script! As the title says, setting the "Windows Go Below" panel setting, makes tiled windows just go behind the panel instead of correctly tiling below it.

**How to Reproduce**
1. Edit panel and set it as "Windows go below"
2. Windows get behind the panel

**Expected behavior**
Windows must go below instead of behind.

**Environment**
 - Distro: Artix Linux (openrc)
 - KWin version: kwin 6.0.4.1-1
 - Krohnkite version: 15e916b
 - List of KWin scripts in use: N/A

**Notes**
Anything that you want to tell developers about.

**Comment by anametologin** [comment]
> Windows must go below instead of behind.

I cannot understand what difference between 'below' and 'behind' in this context. Could you disable the script, reboot and make screenshot with the right window arrangement.
