### ISSUE TITLE
Regression in the Disable Tiling Option

### ISSUE THREAD

**Issue by LechTheMitch** [anametologin/krohnkite#12]
**Symptom**
Adding Screen Number in the Disabling tiling tab does not disable it anymore

**Expected behavior**
Disable tiling on the specified screen after session restart

**Environment**
 - Distro: [Archlinux]
 - KWin version: [6.0.5]
 - Krohnkite version: [0.9.4]

**Notes**
It used to work on 0.9.2, but at the time I had KWin 6.0.4 and I don't have access to the old version of the script to see if the problem is with KWin or the script

**Comment by anametologin** [comment]
I've changed 'number' to 'name' in description. 
![1](https://github.com/anametologin/krohnkite/assets/165245883/8e1c500a-d725-4fef-980c-43435e6feb4f)

**Comment by LechTheMitch** [comment]
Dumb question is the something hidden or the one in System Settings because i used the one in System Settings and it didn't work.
![image](https://github.com/anametologin/krohnkite/assets/104312143/8a8e5a78-f55a-41a5-bbcc-083657224410)

**Comment by anametologin** [comment]
Documentation article: Search a window parameters to filter, float etc.

**Comment by LechTheMitch** [comment]
Ok thank you for developing this script :)
