### ISSUE TITLE
[Wayland] White window as soon as I enable the script

### ISSUE THREAD

**Issue by Haraven** [anametologin/krohnkite#14]
**Symptom**
As soon as I enable Krohnkite from the Kwin Scripts menu, a white window appears on my screen. The window can't be closed or moved. It gets tiled. When viewing its properties, it's a plasmashell window. I tried adding `plasmashell` to the ignore rules - no luck. I also tried adding the class to the floating class rules, but that did nothing. I have tried logging out and back in and restarting. 

The issue persists as long as Krohnkite is enabled - when I disable it and restart, it goes away.

Also, I am not sure if it's at all related, but this window always appears on my second monitor.

**Screenshot**
![ss-30-05-2024_11-46-28](https://github.com/anametologin/krohnkite/assets/10146027/adb6cfe5-fe1b-4390-bcc2-00313b990dc8)

**How to Reproduce**
1. Be in a Plasma Wayland session.
2. Possibly have 2 monitors?
3. Enable Krohnkite.

**Expected behavior**
The plasmashell window should not be tiled and it should certainly not appear as a white window.

**Environment**
 - Distro: OpenSUSE Tumbleweed
 - KWin version: 6.0.4
 - Krohnkite version: latest git (https://github.com/anametologin/krohnkite/commit/a7757e3b6a6074df561fee0442653d865677fd23). I've also tried the version from the KDE Store, with the same result
 - List of KWin scripts in use: just Krohnkite.

**Comment by anametologin** [comment]
Look at this:  https://github.com/anametologin/krohnkite/issues/7
You need to do the same.

**Comment by Haraven** [comment]
That did it! Thanks very much.

Given that this seems to happen to people, please consider adding `xwaylandvideobridge` to the ignored windows list by default.

**Comment by anametologin** [comment]
> Given that this seems to happen to people, please consider adding `xwaylandvideobridge` to the ignored windows list by default.

Added.

**Comment by anametologin** [comment]
> xwaylandvideobridge white rectangle is there

I don't see what's wrong with Krohnkite?

**Comment by Haraven** [comment]
Maybe I posted in the wrong place, I'm not sure.

The original issue was that I had a white window on my screen when enabling Krohnkite. The solution back then was to add `xwaylandbridge` to the ignore rules, which made the white window disappear _completely_. 

Now, I don't have a white window, but a white rectangle, which is persistent on my screen. Maybe it's not a Krohnkite specific issue, I don't know. I thought it was related.

**Comment by anametologin** [comment]
Can you disable Krohnkite and reboot to exclude it.

**Comment by Haraven** [comment]
It's still there even after rebooting. 

So, not a Krohnkite issue. Sorry for the confusion.
