### ISSUE TITLE
Option for panel float.

### ISSUE THREAD

**Issue by Kompreya** [anametologin/krohnkite#19]
**Symptom**
When the KDE Panel is set to float, and a tile touches the panel, it defloats.

**How to Reproduce**
1. Set panel to float.
2. Enable Krohnkite with gap sizes set to a value that causes the tiles to be close to or touches the panel

**Expected behavior**
The expected behavior actually is that the KDE panel defloats when something intersects with its geometry.
See: https://bugs.kde.org/show_bug.cgi?id=462838
https://youtu.be/rhzHLC4VVN0
In Plasma 5.27, I was able to use tilegaps (https://github.com/nclarius/tile-gaps) to force the panel to stay floating. It specifically has an option to consider floating panels.
However, tilegaps is x11 only, including the forked version thats updated for Plasma 6 (https://github.com/audreylandgrave/tile-gaps)

It seems like despite using gaps, KDE Panel has an invisible margin around it when its floating that it checks for intersecting geometry, hence why even when using gaps in krohnkite, if the gap pixel size is under a certain size, it causes the panel to defloat.

The desired behavior is that Krohnkite would consider floating panels similar to how tilegaps does, and not cause panels to defloat when using gaps, regardless of the gap size.

Here's some examples:

Example with gap size too small, causing panel to defloat:
![image](https://github.com/anametologin/krohnkite/assets/41587427/4a5cba44-d91d-4774-81cc-95856cf10989)

Example with a gap of sufficient size as to not cause the panel to defloat (this is the effect Im aiming to achieve):
![image](https://github.com/anametologin/krohnkite/assets/41587427/5fcd6870-096c-4878-90c7-a23e21bae678)

I'd describe this more of a feature request. 

**Environment**
 - Distro: Fedora 40
 - KWin version: 6
 - Krohnkite version: Unsure, I pulled it yesterday though (5/30)

**Comment by anametologin** [comment]
Krohnkite settings -> Geometry->Screen Gaps -> Top -> 20
