### ISSUE TITLE
build issue :

### ISSUE THREAD

**Issue by Maziar123** [anametologin/krohnkite#2]
lastest build :

0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.5.2
2 info using node@v21.7.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/z/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:setEnvs Completed in 0ms
15 timing config:load Completed in 4ms
16 timing npm:load:configload Completed in 4ms
17 timing config:load:flatten Completed in 1ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm run tsc
21 verbose argv "run" "tsc" "--"
22 timing npm:load:setTitle Completed in 0ms
23 timing npm:load:display Completed in 1ms
24 verbose logfile logs-max:10 dir:/home/m/.npm/_logs/2024-04-17T21_48_43_482Z-
25 verbose logfile /home/z/.npm/_logs/2024-04-17T21_48_43_482Z-debug-0.log
26 timing npm:load:logFile Completed in 1ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 15ms
30 silly logfile done cleaning log files
31 timing command:run Completed in 6ms
32 verbose stack Error: Missing script: "tsc"
32 verbose stack
32 verbose stack To see a list of scripts, run:
32 verbose stack   npm run
32 verbose stack     at RunScript.run (/usr/lib/node_modules/npm/lib/commands/run-script.js:94:13)
32 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:61:5)
33 verbose cwd /home/z/Documents/repo/krohnkite
34 verbose Linux 6.8.6-arch1-1
35 verbose node v21.7.2
36 verbose npm  v10.5.2
37 error Missing script: "tsc"
37 error
37 error To see a list of scripts, run:
37 error   npm run
38 verbose exit 1
39 timing npm Completed in 29ms
40 verbose code 1
41 error A complete log of this run can be found in: /home/z/.npm/_logs/2024-04-17T21_48_43_482Z-debug-0.log

**Comment by anametologin** [comment]
What console output after: "make package" ?

**Comment by anametologin** [comment]
In original project "project.json" was gitignored. Add it.
if you have a archlinux. You need four packages: git, make, npm, p7zip for compile package.

**Comment by Maziar123** [comment]
and to now tow typescript
