### ISSUE TITLE
The stack area isn't fully utilized

### ISSUE THREAD

**Issue by suhail-singh** [anametologin/krohnkite#21]
**Symptom**
When two windows are open and one is the master, the window in the stack area occupies only half of the stack as opposed to the entire stack area. Similarly, when there are three windows only 2/3 of the stack is used. 

**How to Reproduce**
1. Launch two windows
2. Make sure one is the master
3. See error

**Expected behavior**
I would expect screen area to not be wasted and for the stack to be fully utilized. 

**Environment**
 - OpenSUSE Tumbleweed snapshot 20240531
 - KWin version: 6.0.5 using Wayland
 - Krohnkite version: ~~0.9.5~~ 0.9.4
 - List of KWin scripts in use: None

**Notes**
Additionally, with only a single window open, it would be helpful if there was an option in tiled layout for that window to occupy the entire screen if it's the master. I.e., for the stack to not occupy any screen real estate if there are no windows in the stack.

**Comment by anametologin** [comment]
Is there an invisible window, may be ?  See https://github.com/anametologin/krohnkite/issues/7. If not,  I need:
1. what layer
2. screenshot
3. log file such as in[ issue 7](https://github.com/anametologin/krohnkite/issues/7)
