### ISSUE TITLE
Makefile `clean` target removes file tracked by git (`package.json`)

### ISSUE THREAD

**Issue by suhail-singh** [anametologin/krohnkite#25]
**Symptom**
In the git repository, `package.json` is being tracked.  However, when one runs
the `make clean` command it gets deleted.  One of these behaviours seems
unintended.  The little that I know about Node development leads me to believe
the Makefile has a bug, but I'm not certain.

**How to Reproduce**
1. Clone the git repository
2. Invoke `make clean`
3. See error

**Expected behavior**
`clean` target should not remove files tracked by git.

**Environment**
 - Distro: OpenSUSE Tumbleweed
 - KWin version: 6.0.5
 - Krohnkite version: `bcabc63`
 - List of KWin scripts in use: None

**Notes**
N/A

**Comment by anametologin** [comment]
Fixed.

**Comment by anametologin** [comment]
res/package.json - joined with the main one and removed.
Makefile - changed
