### ISSUE TITLE
Add ability to configure default layout per screen

### ISSUE THREAD

**Issue by suhail-singh** [anametologin/krohnkite#28]
**Specific pain point**
On vertical displays (across all activities), I find myself repeatedly selecting
the Stacked layout.  It would help for this to be configurable in some sense.

**Possible solution**
A fix for the above could possibly be hard-coded when the screen width is less
than the height.  However, it may be useful, in general, to be able to configure
a default layout based on screen (name).

**Comment by anametologin** [comment]
[make screen by default](https://github.com/anametologin/krohnkite/assets/165245883/f569f1de-1721-4cdf-b3fb-96782a3e3189)

**Comment by anametologin** [comment]
> note this in the README as well

Done

>  it would help if the onscreen display when layout is cycled/switched also noted the screen name along with the layout index number. That would obviate need to open up log viewer to look up details.

Yes, I also thought about it but I abandoned this approach because you need to configure it only once(if you need it at all), but this info is redundant for layout switching.
