### ISSUE TITLE
Windows don't always get tiled when dragged

### ISSUE THREAD

**Issue by HamletDuFromage** [anametologin/krohnkite#29]
**Symptom**
When dragging a window around, it sometimes doesn't automatically tile when releasing it

**How to Reproduce**
1. Drag a window around
2. Release it towards the middle of the screen or in another monitor

**Expected behavior**
It should always consistently tile

**Environment**
 - Distro: Arch Linux
 - KWin version: 6.0.5
 - Krohnkite version: 0.9.5.r2.gdd35653
 - List of KWin scripts in use: None

**Notes**
This can be mitigated by dragging the window where I want it to be and hitting the "tile all" or "toggle tile" shortcut, but it's not ideal. Thank you for resurrecting this script though, overall it's pretty dang good and was much needed

**Comment by anametologin** [comment]
> Drag a window around
It's not declared and supported. The window that is drugged become float immediately

**Comment by HamletDuFromage** [comment]
But it works sometimes. Could it be possible to add an option to allow that that? Maybe force the tiling of that window when it's released? Would you accept a PR for that if you think it's possible?

I can't remember if it worked on all krohnite, but I'm pretty sure it worked on bismuth

**Comment by anametologin** [comment]
> Would you accept a PR for that if you think it's possible?

I have no objections against this feature. Yes.

**Comment by HamletDuFromage** [comment]
Looks like the behavior is defined here: https://github.com/anametologin/krohnkite/blob/dd35653ef7cdc3d715bffa9c8c51982b890cecf7/src/engine/control.ts#L88

If I understand it correctly, if the window is released where another is tiled, then they swap positions and the window is tiled. If it's released more than 30 pixels away from where it was but not on top of another, it's set to floating. In the latter case, I would appreciate a toggle in the settings to disable this behavior (I can give it a try)

There's also `onWindowMove` https://github.com/anametologin/krohnkite/blob/dd35653ef7cdc3d715bffa9c8c51982b890cecf7/src/engine/control.ts#L84 which is currently empty and might need to be populated.

Let me know what you think

**Comment by anametologin** [comment]
> Expected behavior
It should always consistently tile

Yes, I'm not sure about default behavior, but as a option for sure.
