### ISSUE TITLE
keep float windows in top not work true specially dialog box

### ISSUE THREAD

**Issue by Maziar123** [anametologin/krohnkite#3]
sure keep float on top set :

but keep float windows in top not work true specially dialog box really many time not work or override

**Comment by anametologin** [comment]
Are you sure that so-called dialog box actually has "dialog=true" property. You can open Kwin debug console and see all window property there, just to be sure. Also in vertion 0.9.1 you can enable Options->Debug new Windows, the title Search a window parameters to filter, float etc. in readme.md

**Comment by Maziar123** [comment]
yes sure special is problem with dialog box

**Comment by anametologin** [comment]
Could you lay out debug output of this "dialog box" and his parent window here. Also I need screenshot with what's wrong exactly.

**Comment by Maziar123** [comment]
try create it when happen ...

**Comment by Maziar123** [comment]
happen & i am busy to create movie :-(
