### ISSUE TITLE
Question: how to float Firefox extension windows?

### ISSUE THREAD

**Issue by Haraven** [anametologin/krohnkite#32]
I am using Bitwarden for password management. When I want to open my passwords vault, I need to enter my master password. This creates a new window which gets automatically tiled, and I can't figure out how to make it be a floating window.

The window has the `firefox` class, and the only thing that sets it apart from the main browser window is the (lengthy) title:
`Extension: (Bitwarden Password Manager) - Bitwarden — Mozilla Firefox`

I am unsure how to add a rule for this window. I've tried copy pasting the title in the Krohnkite floating rules (in the "By title" section). The input tooltip also said something about substrings, so I tried adding `bitwarden`, `Bitwarden` and `Extension`, and I even tried a regex along the lines of `.*[Bb]itwarden.*`. None of these attempts got my Bitwarden window to float.

Is there any way to get it working? I didn't post this as a bug report because it's not clear to me if I'm doing something wrong or if there's an issue with the Krohnkite rule parsing.

Thanks for your help!

**Comment by Haraven** [comment]
I did enable debug windows but I'm not sure where to get the logs from. I checked the [readme](https://github.com/anametologin/krohnkite?tab=readme-ov-file#search-a-window-parameters-to-filter-float-etc) and saw mention of Kdevelop there, so I installed it. But I don't know what to do from there.

**Comment by anametologin** [comment]
My bad, need KsystemLog. I fixed readme.

**Comment by Haraven** [comment]
Here's the logfile:
[krohnkite.log](https://github.com/user-attachments/files/15806536/krohnkite.log)

The 2 firefox entries should be:
1. opening the browser
2. opening the Bitwarden extension window

**Comment by anametologin** [comment]
try to filter `rambox`

**Comment by Haraven** [comment]
You mean in Krohnkite ignore rules? I did, but it didn't change anything.

If you mean in KSystemLog, there's no entries for rambox.

Rambox is an appimage I'm using, and it's not related to Firefox in any meaningful way. It's set to autostart, which is why it shows up in the log.

**Comment by anametologin** [comment]
> You mean in Krohnkite ignore rules?

yes

> Rambox is an appimage I'm using

If rambox is not a target, there are two firefox windows and they are undistinguished, so you cannot filter appropriate window.

**Comment by Haraven** [comment]
> _there are two firefox windows and they are undistinguished, so you cannot filter appropriate window._

Right, that's precisely my problem. One Firefox window is the main browser window and the second one is the Bitwarden extension window. The only difference between them is the window title, which for the Bitwarden extension window is the string I wrote in my original post:
`Extension: (Bitwarden Password Manager) - Bitwarden — Mozilla Firefox`
(this name is taken using KDE's window properties picker from the Window Rules menu, so the window 100% has that title)

If I try to input the name in Krohnkite's floating rules - by title field, it doesn't work. If you're saying that it doesn't work because the 2 windows are undistinguished by Krohnkite - maybe they should be, at least by title?

**Comment by anametologin** [comment]
> because the 2 windows are undistinguished by Krohnkite 

Not by Krohnkite, but by KWin. Krohnkite only use KWin api. 

>The only difference between them is the window title

KDE has system settings->Window management->Window rules. I advice you play with it.  I piped there  and found a lot of interesting, blocking compositing for example.

**Comment by HamletDuFromage** [comment]
I still can't figure out how to not tile the bitwarden extension window on firefox. I've tried to exclude by title, class etc. Can anyone post a screenshot of the settings GUI with a working config?

**Comment by piotr-dobrogost** [comment]
> EDIT: I just did some testing and tried adding a window rule for the extension window. KDE's Window Rules doesn't affect it either, so maybe it's a bug on their end...

As has been already said Krohnkite uses KWin API and if the above does not work it looks like a bug in KDE itself which should be reported (if not already) and fixed for this to work.

**Comment by anametologin** [comment]
[WIKI](https://github.com/anametologin/krohnkite/wiki/Float-Windows#the-last-stand-194-91-32)

**Comment by piotr-dobrogost** [comment]
Citing from the [wiki](https://github.com/anametologin/krohnkite/wiki/Float-Windows#the-last-stand-194-91-32) referenced above:
> There are situations when Kwin window property window.caption doesn't match with window title

@anametologin 
But somehow Window Rules work in this case. Maybe you could check implementation of Window Rules to see how they much title/caption and use the same method in Krohnkite?

Btw,  I asked at https://app.element.io/#/room/#kwin:kde.org how/when this happens and will update this issue if/when someone answers.
