### ISSUE TITLE
Invisibile window in first virtual desktop

### ISSUE THREAD

**Issue by SamuXzX** [anametologin/krohnkite#37]
**Symptom**
There seems to be an invisible application in the first virtual desktop, which makes it so that one place of the grid is occupied without reason.

https://github.com/anametologin/krohnkite/assets/30182251/4e3cb1e9-d52e-4b93-a7a1-c667fafc6cc3

**How to Reproduce**
1. Enable Krohnkite
2. Open the Overview in the first Virtual Desktop
3. Slowly zoom in the Overview
4. See the frame of an invisible window slowly enlarging.

**Expected behavior**
Not ordinary kinds of windows  shouldn't be counted in the tile system.

**Environment**
 - Distro: Fedora 40
 - KWin version: I don't see it in System Settings. Plasma 6.0.5, KDE Frameworks 6.3.0, Qt 6.7.1
 - Krohnkite version: 0.9.5
 - List of KWin scripts in use: Temporary Virtual Desktops

**Notes**
This reminds me of a problem I noticed some time ago: it seems that the Wayland to X11 Video Bridge counts as a window. It got solved for the other Kwin script I use (https://github.com/Ubiquitine/kwin-scripts/issues/7) and it seems that in Polonium this doesn't happen at all.
I remember seeing the Wayland to X11 Video Bridge invisible window's icon in the Overview in the first versions of Plasma 6, which now just sits in the system tray:
![immagine](https://github.com/anametologin/krohnkite/assets/30182251/cf06a15c-2558-48d4-b495-60560809c1df)

**Comment by sj-w** [comment]
I can confirm this bug. By default, the invisible window blocks the master area of virtual desktop 1. If manually move another window there, then the invisible window will block some space in the slave area.

**Comment by anametologin** [comment]
Could you put the same log as https://github.com/anametologin/krohnkite/issues/7

**Comment by SamuXzX** [comment]
It seems like I don't have KSystemLog installed on Fedora 40. Additionally, I set up windows debug but its seems it disabled itself after the reboot.
Anyway, I added ksplashqml and it worked.

I wonder if you have some way of catching these occurrences without having users to add filters; the guy of Temporary Virtual Desktops seems to have found a way to check if a window is of a "normal" kind, which could filter out all these problems in one go: https://github.com/Ubiquitine/kwin-scripts/issues/7

**Comment by anametologin** [comment]
> I wonder if you have some way of catching these occurrences without having users to add filters; the guy of Temporary Virtual Desktops seems to have found a way to check if a window is of a "normal" kind, which could filter out all these problems in one go: https://github.com/Ubiquitine/kwin-scripts/issues/7

Krohnkite works only with windows with property "normal" and all of this windows which have to be filtered absolutely undistinguished from ordinary windows. The developers of these applications, in my opinion, don't even know about the existence of the tile scripts.

**Comment by SamuXzX** [comment]
Would it be useful to issue a report there asking to properly categorize their windows?

**Comment by stylerw** [comment]
Yes, this is xwaylandvideobridge for me, too. It's not graceful if you need the functionality, but `killall xwaylandvideobridge` makes the window go away.

**Comment by anametologin** [comment]
> Yes, this is xwaylandvideobridge for me, too. It's not graceful if you need the functionality, but killall xwaylandvideobridge makes the window go away.

> It seems to be xwaylandvideobridge. For some reason it's not been excluded 

I've add a little fix, may be this help. Unfortunately I cannot check this by yourself.  As your can see above  `xwaylandvideobridge` developer already make window as dialog. Also you can `make package` and check if my fix will helped.

**Comment by stylerw** [comment]
> I've add a little fix, may be this help. Unfortunately I cannot check this by yourself. As your can see above `xwaylandvideobridge` developer already make window as dialog. Also you can `make package` and check if my fix will helped.

After `make install` from a git clone, this  is now fixed out of the box on Fedora Kinoite 40, without the `killall xwaylandvideobridge`. Thank you!
