### ISSUE TITLE
Brave Doesn't Tile

### ISSUE THREAD

**Issue by nosar77** [anametologin/krohnkite#38]
**Symptom**
Brave browser seems to ignore any tiling setting by the script

**How to Reproduce**
Open brave before opining other applications that do tile
Open other programs first and then brave still doesnt tile

**Expected behavior**
I expect brave to open and tile like every other wind

**Environment**
 - Distro: EndeavourOS
 - KWin version: 6.0.5
 - Krohnkite version: 0.9.5
 - List of KWin scripts in use: dynamic workspaces

**Comment by anametologin** [comment]
Could you put the same log as https://github.com/anametologin/krohnkite/issues/7

**Comment by nosar77** [comment]
Hello, funny story I have the same issue as #7 not sure if its a layout issue but its very similar and the fact that brave wont tile at all. here are the logs 

[krohnkite_logs.txt](https://github.com/user-attachments/files/15930101/krohnkite_logs.txt)
[kwin_logs.txt](https://github.com/user-attachments/files/15930102/kwin_logs.txt)

**Comment by anametologin** [comment]
Are you add  xwaylandvideobridge to  filter by class?

**Comment by nosar77** [comment]
Hello, Yes its enabled by default, as far as the empty space i was able to grab the edges of the windows and stretch them but the layouts and dynamic tiling is all messed up unless im using it wrong. windows dont tile right ill show a video to help you.

**Comment by nosar77** [comment]
So now it seems brave is tiling, im not sure how or why, as long as i dont maximize brave it will tile properly, but if i maximize it takes up the whole screen, other tiling script even forge on gnome has this problem I think as well. but as you can see everything is stuck to the right side of the screen. if i try to drag them it messed up the layout, I just want regular dynamic tiling no special affects i want main window to be on the left then second one opens  to the right and then the 3 window opens on the right and splits the left side with the second window in half.

[Screencast_20240621_193519.webm](https://github.com/anametologin/krohnkite/assets/56127295/f20f0097-393f-4321-a2ab-c374e905d8a3)

**Comment by anametologin** [comment]
try add to filter ksplashqml and reboot

**Comment by nosar77** [comment]
I swear i added the ksplashqml just to test and it didn't fix it but now its fixed. windows are finally tiling properly. I'm still not entirely sure what has been causing these issues and why it randomly started to work. 

![Screenshot_20240621_202701](https://github.com/anametologin/krohnkite/assets/56127295/6f73b358-da71-425f-a929-4b1ca0b1f138)
![Screenshot_20240621_202758](https://github.com/anametologin/krohnkite/assets/56127295/bf7fc6c9-6ca0-495a-b4ad-06c56cf051b1)

One last question before i close this, Im not  sure how the layouts works and cycling the layouts hotkey doesnt do anything, what i want i main screen to be left and then next window opens to the right and then it will split that horizontally on the right so the two on the right one is above and other is below. what layout accomplishes this. Right now what happens when i open a 3rd window is the window ends up floating or stacking on top of the second window. See below

![Screenshot_20240621_203108](https://github.com/anametologin/krohnkite/assets/56127295/4b25a79a-5755-4662-9270-8fb392a029bb)

**Comment by anametologin** [comment]
> I belive is because the settings window I think has a minimum window size so it cant go smaller than that.

Yes it is.

>  I swear i added the ksplashqml just to test and it didn't fix it but now its fixed.

I think the solution is simple - you forgot to reboot. 

>  layouts hotkey doesnt do anything

delete unused shortcuts, see readme 'look at me' title

> what i want i main screen to be left and then next window opens to the right and then it will split that horizontally on the right so the two on the right one is above and other is below. what layout accomplishes this.

you need the default layout - Tile. It has master to the left and split other windows horizontally. As you yourself accurately understood there are windows with min size value and they doesn't fit. I haven't decided what I'll do with them yet. May be I make them float or move to other screen. In any case it is not big problem, you always make them float and move to other screen by shortcut.
