### ISSUE TITLE
Context menu of applets in panel get tiled in new Edit Mode

### ISSUE THREAD

**Issue by SamuXzX** [anametologin/krohnkite#39]
**Symptom**
The new Plasma Edit Mode let us enter the panel configuration view and shows some context menu when hovering on applets in the panel. The problem is that these menus get tiled and maximized, showing their background as the whole screen and their options in the top-left corner.

**How to Reproduce**
1. Enter Panel Configuration
2. Hover on an applet in the panel with the mouse

**Expected behavior**
These context menus shouldn't be tiled nor moves away from their position.

**Environment**
 - Distro: Fedora 40
 - KWin version: I don't see it in System Settings. Plasma 6.0.5, KDE Frameworks 6.3.0, Qt 6.7.1
 - Krohnkite version: 0.9.5
 - List of KWin scripts in use: Temporary Virtual Desktops

**Notes**
Screencast:

https://github.com/anametologin/krohnkite/assets/30182251/b1508865-ea91-4a5b-bf09-d930ba16dc0b

When done in a virtual desktop which has open windows, the context menu gets tiled accordingly: for example, I'm writing this report with just the browser open on the virtual desktop, I try to reproduce the issue and the context menu gets tiled in just half of the screen.

**Comment by anametologin** [comment]
add `plasmashell` to filter by class

**Comment by SamuXzX** [comment]
It worked. I suppose this is another filter to be added by default.
