### ISSUE TITLE
One desktop can't get window to use all space

### ISSUE THREAD

**Issue by tvarsis** [anametologin/krohnkite#4]
**Symptom**
I have a very strange bug where I use 10 different desktops, and on desktop 1 I can't get the windows to fill up the screen and tile correctly. I is like there is always a hidden window that it includes, leaving a blank window space where no actual window can tile into. The strange part is that it only happens on desktop 1 and no other desktops. I have tried to remove and recreate the desktops, removing/cleaning configs files, reinstalling Krohnkite etc. But the issue seems permanent. Is this a know issue? Is there a way where I can reset this behavior if the tiling has somehow got into a bad "stored state" or similar?

**How to Reproduce**
For me it is very reproducible, but I don't have access to any other KDE installations so don't know if it actually is.

**Expected behavior**
Expect windows to always fill up all available desktop space.

**Environment**
 - Distro: Latest OpenSUSE Tumbleweed
 - KWin version: Latest
 - Krohnkite version: Latest
 - List of KWin scripts in use: I have removed all of them, but did have Bismuth and Polonium active before

**Notes**
Here you can see the layout when I have one window open:
![image](https://github.com/anametologin/krohnkite/assets/10090010/b300a99e-dc1c-41e8-a268-014a088ae8a4)

And here you can see when I open next window what happens:
![image](https://github.com/anametologin/krohnkite/assets/10090010/5a1c38ec-de26-4f0c-85d3-482a308928a9)

And then it just keep having that blank space that is untilable.

**Comment by tvarsis** [comment]
Found the issue. It was the xwaylandvideobridge that was the "hidden" window. Once I added that to the Krohnkite exclude rules by class, then everything started working fine. Could be a good idea to add that to the default list of ignore classes since it was a bit of a tricky issue to track down due to the "invisibility" of that app.

**Comment by anametologin** [comment]
in 0.9.2 all windows with hidden property will be filtered. I think it solve the problem.
