### ISSUE TITLE
Info page shows orignal krohnkite  repo link

### ISSUE THREAD

**Issue by soymadip** [anametologin/krohnkite#42]
**Symptom**
If you open kwin scripts page>info of Krohnkite, it will show org esjeon repo link

**Expected behavior**
It should show this repo's link as this is active.

**Environment**
 - Distro: Archlinux
 - KWin version: 6.1.1
 - Krohnkite version:  0.9.7.r5.geb97324
 - List of KWin scripts in use: Desktop change osd,

**Notes**
![image](https://github.com/anametologin/krohnkite/assets/84225810/8f74de3b-0a2c-44d1-9205-0fd109ed3207)

**Comment by anametologin** [comment]
Fixed 34daf1c18f32ee0826085bea6206cfc96c03ac3b
