### ISSUE TITLE
README > Tips > Setting Up for Multi-Screen > Separate Screen Focus

### ISSUE THREAD

**Issue by jotapesse** [anametologin/krohnkite#51]
Hi! The README section **Tips > Setting Up for Multi-Screen** about the step:

> 1. Enable `Separate Screen Focus` feature, the GUI controls are gone since KDE6, but the option is still accessible through the configs: kwriteconfig6 --file ~/.config/kwinrc --group Windows --key ActiveMouseScreen false kwriteconfig6 --file ~/.config/kwinrc --group Windows --key SeparateScreenFocus true

Although the workaround is appreciated, the need for it doesn't seem to be accurate. KDE Plasma 6 did revamp the Settings menus/categories placement but that setting seems to be available at **Apps & Windows** > **Window Management** > **Windows Behaviour** > **Focus** (tab). Screenshot:

![image](https://github.com/user-attachments/assets/555dd378-a4f6-4ce8-80f0-99a6c0446a2e)

Please update the README with that information - will probably help everyone to better configure it. Thank you!

PS: Thank you for bringing back `krohnkite` to Plasma! We really need it. Great job!

**Comment by anametologin** [comment]
e7f7851f8f56f52237db74cb91db126157eada19
