### ISSUE TITLE
Binary tree Layout doesn't allow adjusting layout by resizing windows

### ISSUE THREAD

**Issue by Managor** [anametologin/krohnkite#57]
**Symptom**
Binary Tree would be my preferred tiling algorithm, but the layout doesn't resize by dragging the window edges. Instead the windows just snap back into place

**How to Reproduce**
1. Select Binary tree Layout
2. Attempt to adjust the layout by dragging a window edge

**Results**
The window snaps back into its original place

**Expected behavior**
The layout should adjust around the size of the window

**Environment**
 - Distro: Arch Linux
 - KWin version: 6.1.4
 - Krohnkite version: 0.9.7
 - List of KWin scripts in use: Desktop Change OSD

**Comment by Cal-Nine** [comment]
It also doesn't support rotation

**Comment by d-air1** [comment]
It would also be nice if I could make the insertion point to be the active window so it isn't just going in circles.

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/issues/36#issuecomment-2375616414

**Comment by d-air1** [comment]
> [#36 (comment)](https://github.com/anametologin/krohnkite/issues/36#issuecomment-2375616414)

Just tried it out and definitely lets me get most of the way there, but still a bit more manual than letting btree add windows in the order I want them. Thank you for your efforts.

**Comment by anametologin** [comment]
btree layout will the same as it is, good for watching multiple security cameras in a supermarket or will be completely rewritten by someone.
