### ISSUE TITLE
[Enhancement] Glob pattern for window class matching

### ISSUE THREAD

**Issue by Interpause** [anametologin/krohnkite#58]
As a follow up from my comment https://github.com/anametologin/krohnkite/issues/47#issuecomment-2294551465, I was looking at window rules as a way to float/ignore windows because of the flexibility of the native window matching rules available. An easier alternative (at least for my use case), would be support glob patterns for the window class matching. Relevant part of the code here:

https://github.com/anametologin/krohnkite/blob/1de17a204248afb0be8950f4891c50fc1e8b8c3a/src/driver/kwin/kwinwindow.ts#L38-L68

In my case, I am using waydroid in multi-window mode, which actually works as a "desktop overlay" (It is a normal transparent window with no decorations set to borderless click-passthrough fullscreen). However, as a result, it can be tiled by krohnkite, which breaks the multi-windowness of it:

![image](https://github.com/user-attachments/assets/f7241c7d-79b6-4d3d-a54b-6e2f42c87edd)

I would just exclude "waydroid" in the krohnkite settings if I could, but the issue is waydroid doesn't use "waydroid" alone as the window class. Rather, it appends the android app id to the class, i.e., "waydroid.com.android.vending" or "waydroid.org.wikipedia.beta". Hence, if possible, I would like to be able to ignore "waydroid.*" in the krohnkite settings.

EDIT: For the case of waydroid at least, writing a native window rule for "waydroid.*" that forces waydroid to be fullscreen seems to work well. However, forcing apps to be fullscreen to be excluded is probably not the right solution for most cases besides waydroid.

**Comment by anametologin** [comment]
> I would just exclude "waydroid" in the krohnkite settings if I could, but the issue is waydroid doesn't use "waydroid" alone as the window class

Are you added "waydroid" to the krohnkite settings make reboot and this is not work?

**Comment by Interpause** [comment]
Confirmed adding both "waydroid" and "Waydroid" to Ignore Windows > By Class and restarting fails to exclude waydroid apps from tiling.

**Comment by anametologin** [comment]
Could you make screenshot of your krohnkite settings->rules and do the log: https://github.com/anametologin/krohnkite/issues/7#issuecomment-2126501798 like this

**Comment by Spider19996** [comment]
Hey, the problem is still present here. Any news on this? I don't quite understand how this is supposed to work. I activated “debug new windows” and started KSystemLog but how do I manage to save the correct output? In any case, here is a screenshot of the “rules” window:

![image](https://github.com/user-attachments/assets/b80668d3-3249-42a5-98ff-09b163216dc6)

**Comment by anametologin** [comment]
Try using just `waydroid`, do not need global patterns. 

> I manage to save the correct output

Same as this:  https://github.com/anametologin/krohnkite/issues/7#issuecomment-2126501798
