### ISSUE TITLE
toggle float increases the size of firefox only

### ISSUE THREAD

**Issue by mashrit** [anametologin/krohnkite#59]
**How to Reproduce**
1. Launch 'firefox'
2. Press shortcut 'toggle float'
3. See error

**Expected behavior**
firefox should remain the same size

**Environment**
 - Distro: [endeavour]
 - KWin version: 6.1.4-1
 - Krohnkite version: 0.9.7
 - List of KWin scripts in use: none

**Notes**
this only happens to firefox

https://github.com/user-attachments/assets/dc78078f-579e-4e0d-85e1-9e25d877af2d

**Comment by anametologin** [comment]
Firefox has own shortcuts, maybe this is amazing coincidence. Try change `toggle float` shortcut.

**Comment by mashrit** [comment]
nope, still happens

**Comment by anametologin** [comment]
Make the firefox float and decrease its size by mouse. `toggle float` will retain this size.

**Comment by mashrit** [comment]
does not work, each time i go from tile to float, size of firefox slowly increases

**Comment by mashrit** [comment]
https://github.com/user-attachments/assets/78fe9ea8-63ba-4f0b-a379-b2b6d35d34e9

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/issues/15#issuecomment-2291267778
This have to solve the problem

**Comment by mashrit** [comment]
yes, this one checkbox solved the issue
