### ISSUE TITLE
[question] Is there a way to make the subwindows float by default (without adding exceptions)?

### ISSUE THREAD

**Issue by RudraPS97** [anametologin/krohnkite#6]
Sub windows like batch rename (select more than one items in dolphin and hit F2), preferences windows in some application etc are also tiled. Is there a way to make these float by default? Also, most the things are tiled when you open the Edit mode for desktop.

**Comment by anametologin** [comment]
I found that this kind of Dolphin windows have 'transient' property. In next version I will try make all these windows float.
