### ISSUE TITLE
Pinning a window to all virtual desktops breaks its tiling

### ISSUE THREAD

**Issue by toadtoasted** [anametologin/krohnkite#60]
**Symptom**

When I activate the pin to all desktops shortcut, the tiling of the window breaks,  making it always float. All that toggling float does is make the window slightly smaller. Goes back to normal once the pin is disabled.

**How to Reproduce**
1. Activate the pin to all desktops titlebar button or shortcut
2. Try to do any sort of tiling

**Expected behavior**

Tile as normal while keeping the window on all desktops. (though I can see how this could be an issue when other non-pinned windows on the same monitor are tiled alongside the pinned window.)

**Environment**
 - Distro: Void Linux
 - KWin version: 6.1.4
 - Krohnkite version: 0.9.7
 - List of KWin scripts in use: only Krohnkite

**Comment by anametologin** [comment]
I advise you make float the window before pinning to all desktops. There is not signal "the window was pinning on all desktops" in kwin api, so I cannot subscribe on this action and do appropriate reaction.
