### ISSUE TITLE
Application Menu is tilled when not suppose to be

### ISSUE THREAD

**Issue by matanton666** [anametologin/krohnkite#61]
Hi this probably has an easy solution or just something to add to the ignorelist but I cant seem to fix it

**Symptom**
when i press the hamburger to get to the application menu it opens as a separate tiled window instead of just floating. if i press the shortcut to float it, it returns to the correct position. 

**How to Reproduce**
1. Launch 'any qt app that has an application menu'
2. Press key 'application menu button'
3. See menu tiled

**Expected behavior**
menu is not tiled and is 

**Environment**
 - Distro: [fedora 40]
 - KWin version: [6.1.4]
 - Krohnkite version: [e7f7851]

**Notes**
Iv tried to debug with the logs on startup but couldn't find the window name.

what happens:
![Screenshot_20240828_145548-1](https://github.com/user-attachments/assets/babd86e5-abb7-4321-9b66-bc5d32081d64)

expected:
![Screenshot_20240828_145853-1](https://github.com/user-attachments/assets/4a6455e3-baa6-4bd0-a580-080c935e09b1)

**Comment by anametologin** [comment]
> Iv tried to debug with the logs on startup but couldn't find the window name.

https://github.com/anametologin/krohnkite/issues/7#issuecomment-2126501798 
Try use logs to find appropriate window to filter or lay out it here.
What dolphin version, my version - 24.05.2 and I haven't any such problem.

**Comment by matanton666** [comment]
I dont think this is something to do with dolphin like i said it happens with all applications that have an application menu on the titlebar

> Iv tried to debug with the logs on startup but couldn't find the window name. 

sorry for the confusion, what I meant here is that I could not find krohnkite at all in the logs, I tried again today but it does not appear there. I have done these steps maybe i am doing something wrong:
- open krohnkite settings
- enable `Debug new Windows`
- reboot
- open ksystemlog (journal log)
- hit ignore button
- search for krohnkite (nothing appeared)
- open window, tile it and float it but still nothing appeared in the logs

I have also tried with `Print debug messages` on and to open ksystemlog with root privlages but still could not find the logs. 

I used to have the original Krohnkite extention but recently moved to this repo, could that have an affect?
thank you very much for your time, very appreciated!

**Comment by anametologin** [comment]
> I have done these steps maybe i am doing something wrong

if you have scrupulously followed all the points and do not see any results and krohnkite works that problem in you system. May be logs switched off i don't know, nevertheless you need the logs so I can help you.

> I have also tried with Print debug messages on and to open ksystemlog with root privlages but still could not find the logs.

KWin works with user rights, you need that user 

> I used to have the original Krohnkite extention but recently moved to this repo, could that have an affect?

I don't think so. You remove the old one and install the new one that's it.

**Comment by matanton666** [comment]
turns out its called `kded6`, maybe it could be added to the ignore windows by class list
