### ISSUE TITLE
Improvement: Add .kwinscript to Releases

### ISSUE THREAD

**Issue by Ben9986** [anametologin/krohnkite#63]
Hello, I'm currently looking into creating a Nix package for Krohnkite, if that's okay with you of course. This would be much easier if in the future you could upload the `.kwinscript` file to each release, so that we can avoid downloading NPM dependencies in order to build the script from source. You should just be able to edit the latest release to add it.

I'm happy to mainitain the Nix package in my own time but this one change would make it much easier on the build system!

Thanks

**Comment by anametologin** [comment]
Github do not allow direct upload kwinscript file. Double zip file may be in next version. Also there is  KDE store 'stable' version.

**Comment by Ben9986** [comment]
Hey thanks for the reply. Previous releases before the fork have the kwinscript file which is why i asked. I also just did it on my own [fork](https://github.com/Ben9986/krohnkite/releases/tag/0.9.7) and it worked no problem. Do you mean its against the rules rather than not possible?

**Comment by anametologin** [comment]
>  Do you mean its against the rules rather than not possible?

I figured out what the problem was in my browser extension `umatrix` blocked github subdomain during upload.

**Comment by Ben9986** [comment]
Brilliant thanks for taking the time to look at it.
