### ISSUE TITLE
Make krohnkite tile specific Virtual desktops

### ISSUE THREAD

**Issue by Achno** [anametologin/krohnkite#65]
## Problem
I have 4 virtual desktops and only want the 4th one to be tiled by Krohnkite and the other 3 be unaffected

Essentially im requesting for  a new option  `Disabling Tiling on Desktop`. Example syntax : `screen:Desktop_name` -> `eDP-1:Desktop 1,eDP-1:Desktop 2 ....`

## What i have tried 

 Currently you can disable tiling only on specific screens. To try to mitigate this issue i have created a script which just toggles krohnkite  on/off, so i don't have to visit the settings all the time and when i need to do stuff on my 4th virtual desktop i activate it, but every desktop gets tiled which means i have to resize  manually everything in the other 3 desktops when i disable it.

**Comment by anametologin** [comment]
3f52948d057c2577a44cd22aa97856a7d94c9e76

**Comment by Achno** [comment]
i just tried it out right now, it worked fine after a reboot thank you so much! 

You can can close this issue if you want
