### ISSUE TITLE
Krohnkite causes a flicker when opening any terminal with blur 

### ISSUE THREAD

**Issue by Achno** [anametologin/krohnkite#66]
**Symptom**
Flickers in a terminal with blur 

**How to Reproduce**
1. Setup blur in any terminal 
For `Alacritty`  in `alacritty.toml`: 
```toml
[window]
opacity = 0.85
blur = true
```
For `Kitty` in `kitty.conf`:
```yml
background_opacity 0.85
background_blur 1
```
2. Have Krohnkite enabled
3. Open your terminal and you will see a flicker upon opening

For 

**Expected behavior**
to not have the flicker upon opening a terminal with blur

**Environment**
 - Distro: [Archlinux]
 - KWin version: [kwin 6.1.4]
 - Krohnkite version: [commit: 3f52948 which added ability to ignore vdesktop (though the bug existed before that )]
 - List of KWin scripts in use: [Virtual Desktop only on primary window (i disabled it and i could still reproduce it) ]

**Notes**
The flicker is not noticeable when disabling blur in the terminals . I also Attached a video for visual reference.
EDIT: the bug happens with any window that has blur ex. dolphin 

https://github.com/user-attachments/assets/59282b4b-455b-4c5c-af23-db23279e6f23

**Comment by anametologin** [comment]
I use konsole and kitty and cannot confirm the problem, try another tile script to look the problem persists. I think that the key problem may be in kwin script in general.

**Comment by Ramblurr** [comment]
[Screencast_20240920_115100.webm](https://github.com/user-attachments/assets/052c5213-fcd2-4ae8-904d-56d21f328019)

I'm not sure if this is related, but I have a very bad flicker when using the keyboard shortcuts to move open windows.

The screencast unfortunately does not capture the severity of the issue. In the screencast you can see a small flicker, but in reality that flicker flashes the entire desktop wallpaper underneath with full transparency making it extremely jarring and unsettling.

**Comment by anametologin** [comment]
What terminal emulator are you using?

**Comment by Ramblurr** [comment]
> What terminal emulator are you using?

kitty - https://github.com/kovidgoyal/kitty

However it happens with other applications too: emacs, firefox, konsole

The flicker is always on the right half of the window.

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/issues/66#issuecomment-2335048681
