### ISSUE TITLE
[Enhancement] Rotate Layout with Monitor Orientation/Autorotate

### ISSUE THREAD

**Issue by Cal-Nine** [anametologin/krohnkite#69]
**Symptom**
On a tablet with autorotate, it is necessary to rotate many layouts with the orientation of the display. However when using in tablet mode I don't have easy access to keyboard shortcuts.

**How to Reproduce**
1. Rotate layout of monitor or use autorotate on a 2-in-1 or tablet
2. The screen is divided differently to how it was before and apps may become too small to use.

**Expected behavior**
Screen is divided in the same physical direction, allowing the windows to retain their size and position when rotating.

**Environment**
-  Distro: NixOS
-  KWin version: 6.1.4
-  Krohnkite version: 0.9.7
- List of KWin scripts in use: Just Krohnkite

**Comment by anametologin** [comment]
[KWin Api](https://develop.kde.org/docs/plasma/kwin/api/#kwinvirtualdesktop) hasn't a screen orientation method.
