### ISSUE TITLE
Invisible app or gap taking a window space

### ISSUE THREAD

**Issue by danielskapunk** [anametologin/krohnkite#7]
**Symptom**
In the first desktop, when opening one or more windows there is a gap, like if there were an empty window space

**How to Reproduce**
1. Go to First Desktop
3. Open one window '....'
4. The window does not take full space

**Environment**
 - Distro: KDE neon 6.0 x86_64
 - KWin version: 6.0.4
 - Krohnkite version: 0.9.3
 - List of KWin scripts in use: Desktop Change OSD
 
![issue](https://github.com/anametologin/krohnkite/assets/289055/dfef98fc-ce3a-4e80-88d4-3adfec075ed9)

**Comment by anametologin** [comment]
Documentation article: Search a window parameters to filter, float etc.
Would you enable "debug new windows" and put here actual KSystemLog output of all windows from fresh system start to  the gap appearance.

**Comment by danielskapunk** [comment]
These are the logs of a fresh start with string:krohnkite and string: kwin 
I don't see anything unusual, do you?
Let me know how else can I help with this :)

[krohnkite.log](https://github.com/anametologin/krohnkite/files/15425205/krohnkite.log)
[krohnkite-kwin.log](https://github.com/anametologin/krohnkite/files/15425206/krohnkite2.log)

**Comment by anametologin** [comment]
This window has width: 1 and height: 1, so you can add it to filter.
23/05/24 6:05 P.M.	kwin_wayland	qml: krohnkite:<caption: Wayland to X Recording bridge — Xwayland Video Bridge> <output.name: DP-2> <resourceName: xwaylandvideobridge> <resourceClass: xwaylandvideobridge> ... <size: QSizeF(1, 1)> <width: 1> <height: 1>...

**Comment by danielskapunk** [comment]
that did it :)
I added "xwaylandvideobridge" class to Ignore Windows list
thanks
