### ISSUE TITLE
Krohnkite script makes kwin crash

### ISSUE THREAD

**Issue by zzag** [anametologin/krohnkite#73]
We (KWin upstream) have received a substantial number of crash reports from users who use Krohnkite script https://crash-reports.kde.org/organizations/kde/issues/36968

The culprit seems to be that Krohnkite can access window properties after the window has been closed. It's not supported behavior. Ideally, when a window is closed, a script should drop all its window references.

**Comment by anametologin** [comment]
I have a question. Krohnkite uses windowRemoved(KWin::Window *window) signal.
https://github.com/anametologin/krohnkite/blob/3c546f45065d1b47a0ef077446fa04f91f972eaa/src/driver/kwin/kwindriver.ts#L355-L361

Can I use a given window reference  inside signal's callback function?

**Comment by zzag** [comment]
> Can I use a given window reference inside signal's callback function?

Yes, but you should not do anything about the window, e.g. resize it or make it fullscreen, etc. The `windowRemoved()` signal indicates that the window is _already_ removed.

**Comment by zzag** [comment]
https://invent.kde.org/plasma/kwin/-/merge_requests/6424 addresses the kwin crash, but in general, judging by the crash, the window is used some time after the windowRemoved signal has been emitted

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/issues/79#issuecomment-2380588026

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/issues/79#issuecomment-2393189472

**Comment by anametologin** [comment]
f25caab97f979975e696912cdd65bd83d3f58b6a
