### ISSUE TITLE
[Improvement Request] Improve on BTree layout

### ISSUE THREAD

**Issue by NyaomiDEV** [anametologin/krohnkite#74]
I will preface this improvement request by saying that I migrated from Polonium, which I know has a different implementation of the entire tiling engine - that one leverages KWin whereas Krohnkite and others have their custom written core engine.

There's stuff that Polonium did better with the BTree engine it had, and since this fork of Krohnkite is the only continuation of *any* tiling efforts for KDE, I think it's fair to write about it.

So, here's my list of pain points while using the BTree layout:
- You can't rotate the layout to be top-down. This is not useful on 16:9 or wider setups, but it can be useful in 3:2 displays.
- For the same reason as above, the windows which you want to be "bigger" are always on your left side.
- You can't specify an insertion point. I'd want to have new windows split on the "subdivision" the previous focused window was on, just like Polonium.
- You can't split windows freely. This is especially bad because it means that I have a constrained BTree layout where I have to move windows carefully, but always having the ones I need to be "bigger on screen" to my left. This was a non-issue in Polonium because it allowed me to move my windows (and consequently split if necessary) to any quarter, eighth, etc. of screen.

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/issues/36#issuecomment-2375616414
