### ISSUE TITLE
[Improvement] Choose your default tiling engine

### ISSUE THREAD

**Issue by NyaomiDEV** [anametologin/krohnkite#75]
There should be a way for us to choose our default tiling engine. This was an issue on upstream Krohnkite as well, and I believe it was fixed in Bismuth back then? I am not remembering that well honestly.

**Comment by Ramblurr** [comment]
I believe you mean "layout" and not "tiling engine"?

Anyways, I would like this feature to, that is set default layouts per monitor type.

**Comment by anametologin** [comment]
>  that is set default layouts per monitor type

already implemented, see readme.md
