### ISSUE TITLE
Krohnkite attempts to resize closed windows which occasionally causes Kwin to crash

### ISSUE THREAD

**Issue by Managor** [anametologin/krohnkite#79]
**Symptom**
The kwin devs found out the root cause of what was causing Krohnkite to crash kwin: Krohnkite attempts to resize closed windows. Protections have now been put in place to prevent this from crashing kwin, but resizing closed windows is not what Krohnkite should be doing, thus it should be fixed here too.
Relevant links: https://bugs.kde.org/show_bug.cgi?id=492213
https://invent.kde.org/plasma/kwin/-/merge_requests/6518

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/issues/73

**Comment by anametologin** [comment]
I added some additional conditions (git branch `b_resize_after_delete`). I cannot check if it works by myself, so If someone has the crashes can compile the branch or install (delete `.zip` in the end of file) [krohnkite-0.9.8.1.kwinscript.zip](https://github.com/user-attachments/files/17173936/krohnkite-0.9.8.1.kwinscript.zip)

**Comment by Managor** [comment]
I tried that version and I was still able to create the crash with the Vesktop crash trick.

**Comment by Managor** [comment]
Here are steps to create the crash
- Use the Vesktop 3rd party Discord client. 
- Open at least two Dolphin windows and minimize one of them (might need three with one minized)
- Untile the Vesktop client
- Go into a voice channel
- Start screensharing
As soon as you select which display to share in the screenshare portal, Kwin will crash.

**Comment by anametologin** [comment]
Are you tried disable krohnkite and cast this spell?

**Comment by Managor** [comment]
The crashes started happening after adopting Krohnkite so I'm fairly certain it's the culprit

**Comment by anametologin** [comment]
> The crashes started happening after adopting Krohnkite so I'm fairly certain it's the culprit

I'm very important to know if the crash will happened or not after doing the steps  with  krohnkite disabled. Could you do it?

**Comment by Managor** [comment]
It seems some update might have made it so that I'm no longer able to repo the issue on any Krohnkite version. Damn cherrypicks.

**Comment by anametologin** [comment]
f25caab97f979975e696912cdd65bd83d3f58b6a I don't know what else I can do. Krohnkite checks now if a window has been deleted before adding or resizing it.

**Comment by IDeathByte** [comment]
> Here are steps to create the crash
> 
>     * Use the Vesktop 3rd party Discord client.
> 
>     * Open at least two Dolphin windows and minimize one of them (might need three with one minized)
> 
>     * Untile the Vesktop client
> 
>     * Go into a voice channel
> 
>     * Start screensharing
> 
>     * As soon as you select which display to share in the screenshare portal, Kwin will crash.

i has a similar issue, but without open dolphin/untile vesktop
not sure how to debug it

**Comment by anametologin** [comment]
I'm interested what `Vesktop`  are you using: appimage, flatpak, distribution package or compiled by yourself?

**Comment by Managor** [comment]
`vesktop-electron` from aur. But Iike I said I'm no longer able to use those steps to repro.

**Comment by anametologin** [comment]
> `vesktop-electron` from aur. But Iike I said I'm no longer able to use those steps to repro.

I think Kwin update to 6.1.5-2 solves the issue. So  I close it.
