### ISSUE TITLE
Columns layout cannot be activated

### ISSUE THREAD

**Issue by sr-tream** [anametologin/krohnkite#80]
**Symptom**
This layout cannot be activated by hotkey `Win+\` and cannot be setup be rules.

**How to Reproduce**
1. Enable **Columns** layout
2. Press key `Win+\` or setup this layout in rules
3. Layout is ignored, like disabled

**Expected behavior**
Work **Columns** layout

**Environment**
 - Distro: Archlinux
 - KWin version: 6.1.5
 - Krohnkite version: 0.9.8-6c51c4f
 - List of KWin scripts in use: only Krohnkite

**Notes**
This layout is enabled by default. Re-enable, do not resolve issue (also tried to re-activate script after toggle layout)

**Comment by anametologin** [comment]
1.Have you rebooted your system?
2. Have you tried assign other shortcuts?
3. Is it possible to active other layouts?

**Comment by sr-tream** [comment]
> 1.Have you rebooted your system?

No. I rebooted now - layout is fixed. But, this layout had index less than quarter layout: in setup `monocle,quater,columns,floating` it has indexes `0,2,1,3`

> 2. Have you tried assign other shortcuts?

No.

> 3. Is it possible to active other layouts?

Yes.

**Comment by anametologin** [comment]
> But, this layout had index less than quarter layout: in setup monocle,quater,columns,floating it has indexes 0,2,1,3

In  [0.9.8.1](https://github.com/anametologin/krohnkite/releases/tag/0.9.8.1) you can use layout names .
