### ISSUE TITLE
[Improvment] Idea how to implement layout variants of columns layout

### ISSUE THREAD

**Issue by rkunschke** [anametologin/krohnkite#81]
The new Column layout is great because it allows to create the layout of the windows in a really flexible way. But it does not use the layout variant feature. My idea is to use it as setting for a minimum number of columns to use. To clarify:

**layout [0]**
- fist window spawned -> normal behavior
- second/third/... window spawned -> second window appears under first one as now

**layout [1]** 
- fist window spawned -> normal behavior
- second window spawned -> second window appears beside first one creating a second column
- third/forth/... window spawned -> normal behavior as now

**layout[2]** 
- fist window spawned -> normal behavior
- second window spawned -> second window appears beside first one creating a second column
- third window spawned ->  third window appears beside second one creating a third column
- forth/fifth/... window spawned -> normal behavior as now

**benefits**
This would solve the weirdness (for many people with widescreen displays) with all windows being under each other by default without removing the possibility to do so.

**Comment by anametologin** [comment]
I have plans to implement drop down list in settings: 1 column -> 2 columns...6 columns. User can choose how many columns will created by new windows to begin a new window ordinary creation behavior after this. Also I plan add checkbox `balanced` - create new windows in column with the less number of windows.

the priority task for me now is https://github.com/anametologin/krohnkite/issues/73

**Comment by jotapesse** [comment]
> I have plans to implement drop down list in settings: 1 column -> 2 columns...6 columns. User can choose how many columns will created by new windows to begin a new window ordinary creation behavior after this.

My suggestion would be, if possible, to have this implemented through the Increase/Decrease Master (Columns). We could then dinamicaly change them with the keyboard shortcuts Krohnkite: Increase/Decrease. :smile:

**Comment by rkunschke** [comment]
I am confused about that because the issues regarding that are all closed. Rotating the layout fixes the problem only party.

If I use the layout in **0 degree**, that fixes the problem with windows appearing like in rows (instead addidtional columns -> better for 16/9) but leaves me with a weird layout if I have 3 windows open and a second column added. -> widescreen second row, not possible to create a useful layout with that rotation.
If I use it with **90 degree** the old many rows layout is used when opening windows which is painful on 16/9 aspect ratio, but I am able to create a useful layout.

I think it would be a huge comfort benefit if it would be possible to define a default number of columns/rows

It is unclear if the feature is still planed or rejected for some reason. Is it planned or is it rejected for now?

**Comment by anametologin** [comment]
> Is it planned or is it rejected for now?

This is not rejected. 

> If I use it with 90 degree 

You can rotate the layout on each monitor as you wish, what is problem?

**Comment by anametologin** [comment]
> his was just a argumentation for the extra benefit of the columns-number feature

I don't understand how the default number of columns helps with different rotations on different monitors?

**Comment by rkunschke** [comment]
> > his was just a argumentation for the extra benefit of the columns-number feature
> 
> I don't understand how the default number of columns helps with different rotations on different monitors?

It's more about how a different number of columns and a initial rotation helps to optimize the layout per monitor (different aspect ratios) when you spawn multiple windows without touching the layout altogether. And the benefits that brings us in addition to rotating the layout.
These settings all create ways to manipulate the way how windows are placed initially before creating a additional column manually. So that we need to add columns and rotate layouts less often. So they're both serving the goal to configure the default configuration of a layout.

I didn't wanted to point out a problem about the rotation. I wanted to tell how the rotation and the default column number options would work together to improve the layout in that windows are spawned initially. That was just an argument because i assumed maybe the column number feature is abandoned.

**Comment by chermnyx** [comment]
Let's assume we have the following layout (rotated column layout)
```
XX|XX   -(opening a window)-> XX|XX|XX
XX|XX                         XX|XX|XX
XX|XX                         XX|XX|XX
```

Now For a new window I wanna see something like this or an extra column

```
XX|XX|XX
XX|XX|--
XX|XX|XX
```

Currently there are 2 options with columns layout:
1. Don't set the initial 90° rotation (new window will open vertically) and move every window manually
2. Set the initial 90° rotation; but after opening window 4 I'd have to manually rotate the layout and rearrange all opened windows

**Comment by anametologin** [comment]
@chermnyx , please use `one letter X for one window`, I'm absolutely don't understand  what your point. 

@jotapesse 

> add windows vertically

new windows are added to the same `column` or `horizontal column`. You can move the window left/right/up/down as you wish. If the angle is 0/180 - up/down will create a new `column` (horizontal so-called row), left/right will move the window within the column. If the angle is 90/270 - up/down will move the window within the column, left/right will create a new `column`

**Comment by chermnyx** [comment]
@anametologin
Layout with initial rotation (new windows are opening vertically):

```
X -> X|X -> X|X|X
```

To get from 
![image](https://github.com/user-attachments/assets/45782306-06ed-44de-930a-ca4d2752507a)
to the layout
![image](https://github.com/user-attachments/assets/644522d5-443b-47ff-92fe-55e2a0c64b47)

I need:
1. rotate the layout
2. manually move all windows 

Without rotating the layout I can only do this:
![image](https://github.com/user-attachments/assets/a7d5f53f-2e07-4988-bf0b-edd5324a7396)

**Comment by chermnyx** [comment]
Another option is to change the initial rotation angle but in this case every new window will be opened vertically (under another window in a column)

**Comment by rkunschke** [comment]
@anametologin the screenshots provided @chermnyx are describes what I wanted to say. But I don't thing we need to argue about that because the **feature to define a default number of columns is already planed**... And it solves the problem of needing to rotate the layout to get the layout that @chermnyx and me wanted to use by default. I think @jotapesse meant the same.

@chermnyx @jotapesse Would that feature resolve you're problem or is something different missing? (Than we should create another issue because the feature for this specific issue is already planed)

**Comment by anametologin** [comment]
@chermnyx 
first screenshot - one column
second screenshot - three columns, so now you need to create two columns, but you don't want to create new columns and want to set in configuration - 3 columns?

>  drop down list in settings: 1 column -> 2 columns...6 columns. User can choose how many columns will created by new windows to begin a new window ordinary creation behavior after this

This?

**Comment by jotapesse** [comment]
Hi @anametologin! To me that "horizontal column" concept seems odd, not pratical and probably do not serve the majority of use cases. But still it is the default for some reason.

The screenshots from @chermnyx describe the issue perfectly:

**Initial roation angle: 0º** - You cannot split vertically single columns and add windows to it;
**Initial rotation angle: 90º** - You have to move stacked windows to add columns and then they can be split vertically and add windows to it.

As I commented on this issue: [Four Columns](https://github.com/anametologin/krohnkite/issues/36#issuecomment-2350975742) - to achieve the following example layout:

![image](https://github.com/user-attachments/assets/0b69fbf4-99ab-4709-b633-54f70cab6314)

I have to:

- Start with **Initial rotation angle: 90º** - 1 column with stacked windows;
- Move windows left/right to move that it into a new column;
- You can then add windows to the newly created columns and split them vertically, or move them freely;

Which seems to cumbersome and a huge effort to achieve that layout everytime. So potentially the @rkunschke suggestion for a default or initial number of columns (with initial rotation angle 90º) may be a solution?

**Comment by chermnyx** [comment]
@anametologin
> This

I either wanna create a new column when opening a new window or have a configurable number of the default columns

Something like "b-tree" layout from polonium (which is kinda like the "balanced" layout you describe) would be even better but it might be hard to implement

**Comment by jotapesse** [comment]
@anametologin Another suggestion: what about an option to save the currently configured in use layout on that screen as a custom layout and set it as the default for that screen?

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/releases/tag/0.9.8.4

> to save the currently configured in use layout on that screen as a custom layout and set it as the default for that screen?

this is not planned yet, however you can always save the kde session

**Comment by jotapesse** [comment]
> > to save the currently configured in use layout on that screen as a custom layout and set it as the default for that screen?
> 
> this is not planned yet, however you can always save the kde session

Hi! Thanks, will test the 0.9.8.4 release. Anyway, please consider that suggestion for the future planning: that would probably address the need of everyone else to have typical "custom layout presets" for each monitors by default. The saved KDE session could be a workaround but not really ideal and will not work for new sessions.
