### ISSUE TITLE
[Enhancement] Add an option for tiled layout to put the main window on the right

### ISSUE THREAD

**Issue by Bekaboo** [anametologin/krohnkite#82]
Thank you so much for bringing this script to KDE6!

I really like the tiled layout. However, since the text starts on the left and the main window is also positioned left, I often find myself twisting my neck to read the main window.

I know there's window roration shortcut to "rotate" the main window to the right, but doing this every time I enter a new desktop/after logging in kde feels cumbersome. It would be great if there's an option to place the main window on the right.

**Comment by anametologin** [comment]
implemented. 3d456a6dc11a9782b81d13bfa39ab2936ad9bd01
If you don't want to wait 0.9.8.2 you can  install (remove `.zip` in the end)[krohnkite-0.9.8.1.kwinscript.zip](https://github.com/user-attachments/files/17255718/krohnkite-0.9.8.1.kwinscript.zip)

**Comment by Bekaboo** [comment]
Thanks for your great work!
