### ISSUE TITLE
Moving window via the Move Window Keyboard Shortcut cannot move windows in all positions of the layout

### ISSUE THREAD

**Issue by rkunschke** [anametologin/krohnkite#83]
**Symptom**
When I move my windows with the mouse i often use the Move Window keyboard shortcut (which i trigger with a status bar widget when I am using the mouse only and no keyboard while having my computer connected to my TV) to trigger the window moving. The shortcut places the cursor in the middle of the active window and moves the window. Using this shortcut it is not possible to place window as low on the screen as it needs to be to change the layout in all its possibilitys.
I contrast if i place the cursor on the top section of the window and move it with meta and the mouse it is possible to change the layout in more ways.
I've uploaded a video to show the problem. First part shows usage of the window move shortcut and second part (7 seconds) show the window movement with meta+click on the top section of the window.

https://github.com/user-attachments/assets/d5192fbf-4805-4dc0-8dcf-25066d656d32

I am using the columns layout in my example but I am sure this could happen on other layouts too.

I don't know, maybe it's possible to make the layout changes based on the cursor position instead of the window position to deal with this problem. There is already that xdotool option for resizing the window based on the mouse position. But that is only for resizing and only for x11 and me (and I think most of the users) are already on wayland.
I know that's kind of a corner case but I wanted to report it nerveless.

I've played around with window movement and noticed the problem is really triggered when moving the window with meta+click in general. Based on the position the cursor has on the window that you're moving it is not possible the change the layout in certain ways. The maximum window movement is than limited by the screens edges which can't be exited by the mouse cursor. So I think the problem is present for everyone who moves windows with meta+click.

**Comment by anametologin** [comment]
4f99912e41db8301c60fc2ac3d95521f1ea5e6f0 

(delete zip) 
[krohnkite-0.9.8.2.kwinscript.zip](https://github.com/user-attachments/files/17289715/krohnkite-0.9.8.2.kwinscript.zip)

**Comment by rkunschke** [comment]
This fixes the problem. Thank you for fixing problems in general that fast :)
