### ISSUE TITLE
Reinstall does not restore shortcuts

### ISSUE THREAD

**Issue by holocronweaver** [anametologin/krohnkite#85]
**Symptom**
To debug another issue I was trying to reinstall the script. However after uninstalling and clearing unused shortcuts, when I reinstalled the script the shortcuts were not restored.

**How to Reproduce**
1. Install the script using Kwin Scripts -> Install From File.
2. Remove the script using Kwin Scripts.
3. Clean unused shortcuts: `qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.cleanUp`
4. Install the script using Kwin Scripts -> Install From File.

**Expected behavior**
All the shortcuts to be present and the script to behave as though it were a fresh install.

**Environment**
 - Distro: Kubuntu 24.04.1
 - KWin version: 5.27.11 (I assume Kwin 5 is still supported?)
 - Krohnkite version: 0.9.8.2
 - List of KWin scripts in use: none

**Notes**

Note that I am using KWin 5. I believe that is still supported by this fork, but not certain.

**Comment by anametologin** [comment]
Kwin 5 not supported

**Comment by holocronweaver** [comment]
Please update the README to explicitly mention that Kwin 5 support was dropped. I knew Kwin 6 support was added, but I did not realize Kwin 5 support was dropped.
