### ISSUE TITLE
Option to automatically set the maximum size when floating a window?

### ISSUE THREAD

**Issue by piotr-dobrogost** [anametologin/krohnkite#86]
Currently when one floats a window (<kbd>Meta</kbd>+<kbd>F</kbd>) it restores to its original size before it has been tiled. From what I see this original size often is the size that comes from it being tiled previously in some other layout. This behavior is surprising and I guess most of the time one wants the floated window to be of maximum size (without being marked as Maximized).
What do you think about automatically setting the maximum size for floated window?
Or leaving 5-10 pixels from screen edges so that one can clearly see that the window is floating as opposed to being Maximized or being displayed in Monocle layout?
Btw, does anyone know how to set maximum size for a windows with a shortcut without entering Maximized state at the same time (I also asked here https://discuss.kde.org/t/how-to-set-maximum-windows-size-without-setting-maximized-property/23090)?

**Comment by anametologin** [comment]
I'm answered you in discussions https://github.com/anametologin/krohnkite/discussions/88
