### ISSUE TITLE
Current layout shown as Monocle (in OSD) both when activating and when deactivating Monocle layout

### ISSUE THREAD

**Issue by piotr-dobrogost** [anametologin/krohnkite#87]
When I keep pressing <kbd>Meta</kbd>+<kbd>M</kbd> Monocle layout is alternately activated and deactivated but after each press I see Monocle name in the middle of the screen. Shouldn't that be alternately Monocle and the name of the other layout which is being activated when Monocle is deactivated?

**Comment by anametologin** [comment]
8fec2e326e648f954aa0b39c07dd3e2dbd48adc4 fixed
