### ISSUE TITLE
No log entries after turning "Debug new Windows" option on

### ISSUE THREAD

**Issue by piotr-dobrogost** [anametologin/krohnkite#94]
After following instructions in README's section [Search a window parameters to filter, float etc.](https://github.com/anametologin/krohnkite?tab=readme-ov-file#search-a-window-parameters-to-filter-float-etc
) there are no entries in the log when filtering using `krohnkite` word in KSystemLog.

In the journal (after running`journalctl`) I noticed this which might be related:
```
paź 08 12:39:13 fedora kwin_wayland[43472]: qt.qml.usedbeforedeclared: file:///home/piotr/.local/share/kwin/scripts/krohnkite/contents/code/script.js:48:9 Variable "DEBUG" is used before its declaration at 3115:7.
```

Fedora 41
KWin 6.2.0
Krohnkite 8fec2e2

**Comment by anametologin** [comment]
`Variable "DEBUG" is used before....` don't affect on Krohnkite work or debug. Try filters: `qml` and `kwin` you have to see `qml: KROHNKITE: starting the script` with debug or not.Try reboot system. Anyway it's not Krohnkite problem, if KSystemLog doesn't work properly,  may be there is something else. You need `journald` log, unit: `kwin-wayland`.

**Comment by piotr-dobrogost** [comment]
I'm observing lack of log messages on two different systems, both with Fedora 41 and KWin 6.2.
Can someone with KWin 6.2 check if it works or confirm it doesn't?

**Comment by phord** [comment]
Try adding this custom rule, to unblock your original problem:

    kwin_*.debug=true

I did not try logging out/in after making the changes to my kdebugsettings, but I definitely noticed they did not take effect immediately.  They took effect after a restart.  Maybe a logout/login is enough, but did you try restarting?

**Comment by piotr-dobrogost** [comment]
> Try adding this custom rule, to unblock your original problem:
> 
> ```
> kwin_*.debug=true
> ```
> 
> I did not try logging out/in after making the changes to my kdebugsettings, but I definitely noticed they did not take effect immediately. They took effect after a restart. Maybe a logout/login is enough, but did you try restarting?

I tried `kwin_*.debug=true` and `*.debug=true` with restarting computer and neither helped.

**Comment by piotr-dobrogost** [comment]
I raised this issue at
https://discuss.kde.org/t/debug-messages-from-kwin-script-using-console-log-not-present-in-the-journal-in-spite-of-setting-full-debug-in-kdebugsettings/23666
and
https://bugs.kde.org/show_bug.cgi?id=494870

**Comment by piotr-dobrogost** [comment]
@luisbocanegra suggested in his [comment](https://discuss.kde.org/t/debug-messages-from-kwin-script-using-console-log-not-present-in-the-journal-in-spite-of-setting-full-debug-in-kdebugsettings/23666/12?u=piotr_dobrogost) to set `qml.debug=true` in `~/.config/QtProject/qtlogging.ini` and that solved the problem. Btw, custom rules set in KDebugSettings are saved in this file so alternatively one can add this rule there with the same result.

I still have no idea why setting more generic rule `*.debug=true` does not work but setting more specific one `qml.debug=true` works?
