### ISSUE TITLE
Detach GitHub fork to increase discoverability

### ISSUE THREAD

**Issue by emosenkis** [anametologin/krohnkite#96]
Searching on Google for kronkite only returns results from the old repo. Perhaps asking GitHub to [detach the fork](https://support.github.com/request/fork) will allow this repo to feature more prominently in Google search results.

**Comment by anametologin** [comment]
https://github.com/anametologin/krohnkite/discussions/71

**Comment by piotr-dobrogost** [comment]
This issue is not about renaming the project but about making it independent of the original one.

**Comment by anametologin** [comment]
this project is just a fork and will remain so until the end. `Searching on Google` doesn't work  - bad, there is the filter - good.
