### ISSUE TITLE
Dialog style config-windows stuck in background when using the floating layout

### ISSUE THREAD

**Issue by ChaosNicro** [anametologin/krohnkite#97]
**Symptom**
Some window classes, such as krohnkite configure dialog appear behind all other windows with no way to pull them to the foreground. This seems to only happen in the floating layout.

**How to Reproduce**
1. Enable Krohnkite
2. Switch to the floating layout
3. Open the krohnkite options panel
4. Observe it being obscured by the kwin scripts window

**Expected behavior**
The floating layout should mimic a non-krohkite desktop, where the focused window is in the foreground unless configured otherwise.

**Environment**
 - Distro: Opensuse Slowroll
 - KWin version: 6.1.5
 - Krohnkite version: 0.9.8.3 release
 - List of KWin scripts in use: No others active

**Notes**
The option to float utility windows does not affect this. I'm new to tiling, so I'm sorry if this is a misunderstanding.

**Comment by anametologin** [comment]
Could you post the video with problem, I cannot confirm it.

**Comment by ChaosNicro** [comment]
Sure. Here I enable Krohnkite and open it's configure dialog as well as the kmenu dialog. Both work as expected. I then switch to floating layout and try the same, with the problem present. Opening a full app like Dolphin does not trigger it but any settings-panel seems to.  

https://github.com/user-attachments/assets/56607143-b6a7-45fc-a7d2-90dd69dc8eca

**Comment by anametologin** [comment]
Try uncheck Krohnkite settings->Options->Keep floating windows above tiled windows

This option make all floating windows `Keep above others' option on, but all windows you in ignore lists not getting this option because Krohnkite doesn't rule them.

**Comment by ChaosNicro** [comment]
That is the change I was looking for. Kinda odd, that it's a default setting, though I guess the floating layout isn't really meant to be used extensively. Thanks.

**Comment by piotr-dobrogost** [comment]
I was planning to write that _Keep above others_ option is **not** the solution to this problem but meanwhile issue #104 has been raised with very good explanation of the original problem in krohnkite regarding layering windows.
