### ISSUE TITLE
mpv flickers when switching media in playlist

### ISSUE THREAD

**Issue by pjhfggij** [anametologin/krohnkite#99]
**Symptom**
when mpv window is tiled it noticeably flickers between switching media in a playlist

**How to Reproduce**
1. Launch `mpv *`
2. tile the window
3. Press key `>` to play next video/image
4. See error, mpv window flickers

**Expected behavior**
Switching would be as smooth as it is when window isn't tiled

**Environment**
 - Distro: Archlinux
 - KWin version: 6.2.2
 - Krohnkite version: 0.9.6 8aed7a5
 - List of KWin scripts in use: none other than Krohnkite

**Comment by anametologin** [comment]
I cannot confirm this problem, there was couple issues about flickering windows with transparency. I haven't any flickering at all. I think the problem may be in kwin-kde-kernel-drivers-linux-world, not krohnkite imho/

**Comment by pjhfggij** [comment]
thanks @anametologin it turned out that --no-auto-window-resize had to be passed to mpv to prevent it from auto-resizing the window to fit media resolution. Closing
